version: '3.9'
services:
  snapmap-api:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: