version: '3.9'
services:
  dynamodb-local:
   image: "amazon/dynamodb-local:latest"
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   container_name: dynamodb-local
   env_file:
    - .env
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal

  snapmap-api:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    env_file:
      - .env
    volumes:
      - .:/app